feat(APIKeys: (67) Added API Key UI
sensorbucket/SensorBucket pull request #69
Opened 2024-01-05 13:58 UTC by JEFFTheDev

Some thoughts:

- Maybe we need to discuss some standardized way of form validation now that we're adding more user generated content features. Currently I've used the snackbar which works fine but best practice might be to have some error messages in the form itself
- In this PR I chose to have the frontend self-service be a seperate running go program, as discussed this will be changed to be served from a seperate port but still be available from the same program. When our UIs merge we will fix this, same goes for the generic layout package.

2024-01-05 13:59 UTC, JEFFTheDev commented on services/tenants/dashboard/main.go
> +
this whole file can be ignored since we're gonna merge this into the tenants service

2024-01-12 15:06 UTC, TimVosch requested changes

2024-01-12 15:06 UTC, TimVosch commented on services/tenants/dashboard/routes/api-keys.go
> +		id, err := strconv.ParseInt(tenantId, 10, 32)
32 or 64 for ID? also see migratins

2024-01-12 15:06 UTC, TimVosch commented on services/tenants/dashboard/views/apiKeysCreatePage.qtpl
> +{% import "sensorbucket.nl/sensorbucket/pkg/layout" %}
Add a checkbox for "Expires" and use hyperscript to enable or disable the expiry input. The checkbox valueis purely frontend and does not have to go to the backend.

2024-01-12 15:06 UTC, TimVosch commented on services/tenants/dashboard/routes/api-keys.go
> +			layout.SnackbarSomethingWentWrong(w)
log

2024-01-12 15:06 UTC, TimVosch commented on services/tenants/dashboard/routes/api-keys.go
> +}
TODO

2024-01-12 15:06 UTC, TimVosch commented on services/tenants/dashboard/static/codemirror.js
can eb removed?

2024-01-15 07:08 UTC, JEFFTheDev commented on internal/pagination/pagination.go
> +	// meaning a new cursor is sent that won't result in any data
https://github.com/sensorbucket/SensorBucket/issues/82

2024-01-23 16:02 UTC, merged